# ft-nixlaunch — MangoWC DE integration
#
# Writes a keybind declaration for ft-nixlaunch into the MangoWC keybind
# config file.  MangoWC uses a Hyprland-compatible config syntax, so the
# keybind format follows the same `MODIFIER, key` convention.
#
# The generated file is sourced automatically when MangoWC starts, provided
# you have the following line in your main mangowc.conf:
#
#   source = ~/.config/mangowc/ft-nixlaunch-keybind.conf
#
# This file is managed by Home Manager — do not edit it directly.
{ config, lib, ... }:

let
  cfg  = config.programs.ft-nixlaunch;
  mCfg = cfg.integrations.mangowc;
in

{
  options.programs.ft-nixlaunch.integrations.mangowc = {

    keybind = lib.mkOption {
      type        = lib.types.str;
      default     = "SUPER, space";
      example     = "SUPER, F2";
      description = ''
        MangoWC keybind that launches ft-nixlaunch.
        Uses MangoWC's `MODIFIER, key` format, which is the same as Hyprland.

        Examples:
          "SUPER, space"
          "SUPER SHIFT, F2"

        Only active when `integrations.de = "MangoWC"`.
      '';
    };

    extraRules = lib.mkOption {
      type        = lib.types.lines;
      default     = "";
      example     = "layerrule = blur, rofi";
      description = ''
        Additional raw MangoWC config rules appended to the generated keybind
        file.  Use this for compositor rules specific to the ft-nixlaunch layer
        (e.g. blur, animations) that are not exposed as module options.
      '';
    };

  };

  config = lib.mkIf (cfg.enable && cfg.integrations.de == "MangoWC") {
    # Write a standalone keybind snippet that MangoWC can source.
    # Keeping it in a separate file avoids touching the user's main
    # mangowc.conf and makes it easy to regenerate on theme changes.
    xdg.configFile."mangowc/ft-nixlaunch-keybind.conf".text = ''
      # ft-nixlaunch keybind — generated by Home Manager, do not edit
      bind = ${mCfg.keybind}, exec, ft-nixlaunch
    '' + lib.optionalString (mCfg.extraRules != "") ''

      # Extra rules
      ${mCfg.extraRules}
    '';
  };
}
